services:
  # creating service for the pulled image from dockerhub using its IMAGE_ID
  matrix: 
    image: ${IMAGE_ID}
    ports:
      - 3000

  # creating service for nginx image to load balance the requests  
  nginx:
    image: nginx:latest
    volumes:
      - ./logs:/var/log/nginx     # mounting the container logs to persistent storage
      - ./nginx.conf:/etc/nginx/nginx.conf  # mounting the custom nginx configuration   
    depends_on:
      - matrix
    ports:
      - 3000:3000

